### ISSUE TITLE
qcoder projects

### ISSUE THREAD

**Issue by elinw** [ropenscilabs/qcoder#10]
Say a user has 3 different projects, how do we keep them straight and usable?
What does a project consist of?

- text files (aka the data) that all need to be in the same folder. 
- code file, possibly stored as csv? 
- data frames such as the coded data, data on units, mapping files.
- other?

We need to decide on a way to handle these and maybe have a function to initialize a project that creates all the folders, empty data sets and so on.

**Comment by Lingtax** [comment]
Like a custom ProjectTemplate::create.project() perhaps? 
https://github.com/KentonWhite/ProjectTemplate

**Comment by elinw** [comment]
That looks cool

**Comment by Lingtax** [comment]
Might be able to then create some precautionary defaults (e.g. .gitignore the contents of the data folder), so users don't accidentally push data into the open?

**Comment by elinw** [comment]
Great idea.

**Comment by elinw** [comment]
So far I've added a basic project concept and a function to set up some folders.

![folderstructure](https://user-images.githubusercontent.com/754813/40882901-906f2b6c-66bd-11e8-91e7-fb8afeb8c027.png)

**Comment by elinw** [comment]
I'm going to close this, because the basic infrastructure is there, though we will certainly be discussing implementation details and what a project should look like.
