### ISSUE TITLE
Thinking through hypothes.is as an interface for coding

### ISSUE THREAD

**Issue by jduckles** [ropenscilabs/qcoder#13]
Twitter thread on the topic https://twitter.com/judell/status/999817415390216192

**Comment by elinw** [comment]
It's a cool interface, but  I don't think it fits the definition of light weight for our persona of a grad student with 50 interviews to code and never used R before.   But as we go it's  worth thinking about their UI.

**Comment by elinw** [comment]
I'm closing this as an issue for now but I do think that the UI model has potential.
