### ISSUE TITLE
qcode() restricts directory choice

### ISSUE THREAD

**Issue by pauljohn32** [ropenscilabs/qcoder#130]
after qcode(), the user HOME folder is displayed for selection of qcoder projects. This is a fail for me because projects are not loaded within my HOME folder, they are on a server share in another location.

**Comment by elinw** [comment]
Is that a second volume or the same volume?

**Comment by elinw** [comment]
Just reading some issues over at the shinyFiles repo ... what do you think of an option to enter the path as a string? https://github.com/thomasp85/shinyFiles/issues/53

On the other hand, the reason that there is the qcoder_custom app is precisely for typed interactions with data in different locations.  However that app is currently neglected while we work on cleaning up a number of issues in the main qcoder app.  Still, possibly we could add a typed field as a temporary measure if you think that would work.

**Comment by elinw** [comment]
@pauljohn32 I'd mention actually that you can always use the command line functions to read in data from anywhere.
