### ISSUE TITLE
'Add data' tab functionality

### ISSUE THREAD

**Issue by Jones-Git** [ropenscilabs/qcoder#131]
- [BUG] 'Add data'>'Add new document'>'Select File' crashes upon choosing a document and hitting select.
Error message:  _Warning: Error in <-: replacement has length zero_ reference an issue found in app.R line#350

- [SUGGESTION] 'Add data' tab allows for input of units and codes before user has selected 'my_qcoder_project' folder. Upon choosing the project folder, the codes and units are amended to the project. Should rather have the user add their project folder first before being able to do anything within 'Add data' tab.

- [SUGGESTION] 'Add new unit' field should not be allowed to be added when left blank.

**Comment by elinw** [comment]
I wonder if we should just not show any tabs (or make them unclickable) if a valid project is not selected.

**Comment by Jones-Git** [comment]
I really like the idea of the tabs being disabled whilst no project is loaded. It can be greyed out and un-clickable. Perhaps a little prompt comes up every time the user clicks on one of the tabs telling them "You must first select your project folder."

**Comment by elinw** [comment]
Closed by #154
