### ISSUE TITLE
just a note

### ISSUE THREAD

**Issue by jwijffels** [ropenscilabs/qcoder#171]
FYI. The crfsuite R package which basically does entity recognition also has a shiny app for doing annotation:

```
install.packages("crfsuite")
install.packages("shiny")
install.packages("flexdashboard")
rmarkdown::run(file = system.file(package = "crfsuite", "app", "annotation.Rmd"))
```

This looks as follows: 

![app-screenshot](https://user-images.githubusercontent.com/1710810/62289809-ff527e80-b45f-11e9-95bc-9b6878e757bb.png)

**Comment by elinw** [comment]
Oh that does have some similar ideas even though it's for a different purpose.  Looks really nice.

**Comment by jwijffels** [comment]
I think it's pretty much the same. Only difference in the output is that the crfsuite app stores the start/end position of the selected text alongside the category and the selected text itself.

**Comment by elinw** [comment]
Yes, our architecture is  different although the appearance is similar.

**Comment by jwijffels** [comment]
Closing. As you are now aware of that alternative.
