### ISSUE TITLE
Unable to add units, data or codes. 

### ISSUE THREAD

**Issue by GovernorUnfortunable** [ropenscilabs/qcoder#200]
-----------------
I am having some troubles with Qcoder. I must say that I am new using it, so I might be missing something. Anyways, I could not find a way around this. When I try to add data (by selecting a .txt file), units or codes, it crashes. I get a black screen. Nothing happens, so I need to go back to RStudio and stop the process. Any clues? I am running this in RStudio (Version 1.2.5033) and R (4.02).
This is the messege I get:
```
Warning in gzfile(file, "rb") :
  cannot open compressed file '/Users/segundosombra/AVINA_OpenData/data_frames/qcoder_documents_AVINA_OpenData.rds', probable reason 'No such file or directory'
Warning: Error in gzfile: cannot open the connection
  76: gzfile
  75: readRDS
  74: qcoder::add_new_documents
  73: observeEventHandler [/Library/Frameworks/R.framework/Versions/4.0/Resources/library/qcoder/shiny/qcoder/app.R#432]
   2: shiny::runApp
   1: qcode
```

**Comment by elinw** [comment]
Do you have the files set up in the folders as described? Are you talking about starting a new project or one that you've already created  and are coming back to?

**Comment by GovernorUnfortunable** [comment]
Thanks. It was a new project; files were in a different directory. I can't say much more; I switch to another software afther this problem.

**Comment by elinw** [comment]
Okay thanks
