### ISSUE TITLE
Package issues

### ISSUE THREAD

**Issue by markchand** [ropenscilabs/qcoder#201]
Hi folks - I'm just getting qcoder up and running and hit a snag right out of the gate, which is that some update to magrittr means it has to be loaded separately in order to run line 24 of README.Rmd: 

`qcode()`

**Comment by elinw** [comment]
Okay let me have a look at this.

**Comment by elinw** [comment]
I didn't have a problem with the `qcode()` command ... had you already created a project and imported data?  I'm on magrittr 2.0.1 is that the version you are on?

**Comment by markchand** [comment]
Looks like I'm on 2.0.1 now. I'm not sure what happened the first time around, and I can't replicate the error--am wondering if having a previous version of magrittr installed might be the issue. In any case, resolved! and on to the next bit of red ink.

**Comment by elinw** [comment]
Please make sure to send feedback etc.  Happy to see people using this!
