### ISSUE TITLE
Button for adding a new code should be below fillable fields

### ISSUE THREAD

**Issue by stragu** [ropenscilabs/qcoder#210]
This is the current look of the "Add data" tab:

![image](https://user-images.githubusercontent.com/1747497/115831977-a7d71c00-a455-11eb-8406-39c15d99ab31.png)

I believe it would be more consistent and logical to have the "Add code" button below the "Code" and "Description" fields, because:

- That's the case with the "Add new unit" section
- People usually go through the page in the top-to-bottom direction: fill the fields first, then confirm by clicking the button. My pull request #208 would result in this:

![image](https://user-images.githubusercontent.com/1747497/115832294-13b98480-a456-11eb-8dee-88b1810dbfc4.png)

**Comment by elinw** [comment]
Got it, that makes sense.

**Comment by stragu** [comment]
Pull request has been merged, so closing.
Cheers @elinw !
