### ISSUE TITLE
Create UI for editing codes

### ISSUE THREAD

**Issue by changecase** [ropenscilabs/qcoder#221]
It is easy to add a code via the UI with a mistake in the description. There isn't a way to edit the code description via the UI.

Provide users with the ability to edit code descriptions via the UI.

**Comment by elinw** [comment]
Happy to take a code contribution for this.  It has been on my list. I believe it is do-able by changing the datatable settings.

**Comment by elinw** [comment]
#225 should now allow editing of the descriptions.  If you reinstall it should work now.
I deliberately did not allow editing of the codes themselves.
