### ISSUE TITLE
problem with trying qcoder

### ISSUE THREAD

**Issue by FrdVnW** [ropenscilabs/qcoder#45]
I have a problem when launching qcode (after import data). The program seems to try to find a file : "/data_frames/qcoder_documents_.rds" (without taking my project name ?). 
Shiny app is launching, but it stay gray and I cannot select any folder.

> Listening on http://127.0.0.1:7580
Warning in gzfile(file, "rb") :
  impossible d'ouvrir le fichier compressé '/data_frames/qcoder_codes_.rds', cause probable : 'Aucun fichier ou dossier de ce type'
Warning: Error in gzfile: impossible d'ouvrir la connexion
  75: gzfile
  74: readRDS
  73: observeEventHandler [/home/fred/R/x86_64-pc-linux-gnu-library/3.4/qcoder/shiny/qcoder/app.R#146]
   2: shiny::runApp
   1: qcode
Warning in gzfile(file, "rb") :
  impossible d'ouvrir le fichier compressé '/data_frames/qcoder_documents_.rds', cause probable : 'Aucun fichier ou dossier de ce type'
Warning: Error in gzfile: impossible d'ouvrir la connexion
  116: gzfile
  115: readRDS
  114: <reactive:my_choices> [/home/fred/R/x86_64-pc-linux-gnu-library/3.4/qcoder/shiny/qcoder/app.R#116]
   98: my_choices
   93: renderUI [/home/fred/R/x86_64-pc-linux-gnu-library/3.4/qcoder/shiny/qcoder/app.R#123]
   92: func
   79: origRenderFunc
   78: output$choices
    2: shiny::runApp
    1: qcode

**Comment by elinw** [comment]
Thanks will check this out.  I take it you were using your own documents etc, can you tell me the file names and locations?

**Comment by sashadb** [comment]
I am having a similar problem, just trying the package for the first time with the sample project.

The shiny app will appear for one second and then disappear.

I also received an earlier warning message when importing the sample project. It may be unrelated.

`> import_project_data(project = "my_qcoder_project")
Parsed with column specification:
cols(
  code_id = col_integer(),
  code = col_character(),
  code.description = col_character()
)
Parsed with column specification:
cols(
  unit_id = col_integer(),
  name = col_character()
)
Parsed with column specification:
cols(
  doc_path = col_character(),
  unit_id = col_integer()
)`

**Comment by elinw** [comment]
Can you both please try with the current version, I just did a lot of fixes.    The messages are not warnings they are just routine messages from `readr` though I agree I would like to make them go away! 
@FrdVnW  @sashadb

**Comment by sashadb** [comment]
I am still getting the same error message as Fred. I removed the package and re-installed.

`Listening on http://127.0.0.1:3681
Warning in gzfile(file, "rb") :
  cannot open compressed file '/data_frames/qcoder_codes_.rds', probable reason 'No such file or directory'
Warning: Error in gzfile: cannot open the connection
  75: gzfile
  74: readRDS
  73: observeEventHandler [/Library/Frameworks/R.framework/Versions/3.5/Resources/library/qcoder/shiny/qcoder/app.R#152]
   2: shiny::runApp
   1: qcode
Warning in gzfile(file, "rb") :
  cannot open compressed file '/data_frames/qcoder_documents_.rds', probable reason 'No such file or directory'
Warning: Error in gzfile: cannot open the connection
  116: gzfile
  115: readRDS
  114: <reactive:my_choices> [/Library/Frameworks/R.framework/Versions/3.5/Resources/library/qcoder/shiny/qcoder/app.R#122]
   98: my_choices
   93: renderUI [/Library/Frameworks/R.framework/Versions/3.5/Resources/library/qcoder/shiny/qcoder/app.R#129]
   92: func
   79: origRenderFunc
   78: output$choices
    2: shiny::runApp
    1: qcode`

**Comment by elinw** [comment]
So it's not finding your project name.  Can you check to see if the dataframes folder inside your project folder contains files and tell me their names?

**Comment by elinw** [comment]
@FrdVnW @sashadb I  reproduced your error message, am working on a solution now.

**Comment by elinw** [comment]
I think this is somewhat operating system dependent and I tested on both my mac on a Centos server.  It now seems to be working.  This seems to be related to how the file select is working.    Please try it now.

**Comment by sashadb** [comment]
Great! It works now for me on my mac. Thanks

**Comment by FrdVnW** [comment]
Thanks also, it seems ok for me now on Linux/Ubuntu. I will try your package in substitution of RQDA in the workflow of my approach (CMASOP), for building cognitive maps. Maybe future integration/collaboration will be interesting/posisble.
