### ISSUE TITLE
No more 'add code' tab

### ISSUE THREAD

**Issue by FrdVnW** [ropenscilabs/qcoder#58]
Hi there, 
I started a project with sample as in Readme. I can select a project/file (sample)
I don't see how to add a 'code', there is no more 'sub-tab' in 'Codes' (I saw it existed before in the help).
I can added one in editing the text adding a new free text after the '#' during the 'coding' process.
I saw a new 'add data' for new doc and unit, but no for 'new code'

**Comment by elinw** [comment]
I think there's already an issue for that.  I want to think about how to make it so you can also add a description to a code you've added by just adding it to a document.  (THe old add code tab was empty I think.)

**Comment by FrdVnW** [comment]
Ok, yes, I open the 'qcoder-custom' and see in the code that it is empty. 
I will close this issue then. We can stay in contact, I really want to contribute to this package development.
