### ISSUE TITLE
Updating project data

### ISSUE THREAD

**Issue by FrdVnW** [ropenscilabs/qcoder#59]
Hi there, 
As stated in the readme : 'You must restart the qcode application to update those displays. This is a high priority development item.'

For me, it was linked to the adding of a new code, but during the process of coding. I think it could be great to have more reactivity. I had to re-open the project (select....) for seeing changes in tables / in the coded text. 
I proposed a pull request linked to this issue. It may be not the ideal, but a statring point : an 'update' button right beside the 'select button'.

**Comment by elinw** [comment]
thanks
