### ISSUE TITLE
No data frame qcoder_document created on windows

### ISSUE THREAD

**Issue by FrdVnW** [ropenscilabs/qcoder#66]
Hi there,
trying the package on windows, it seems that the `create_qcoder_project` does not generate the qcoder_documents_my_qcoder_project.rds in the data-frame folder. I get this error in terminal when selecting the project in the app.

> cannot open compressed file 'C:/Users/fvanw/Projects/qcoder-test/my_qcoder_project/data_frames/qcoder_documents_my_qcoder_project.rds', probable reason 'No such file or directory'

**Comment by elinw** [comment]
Okay I will take a look when I am on my windows machine next week.  Is it finding the current working directory?

**Comment by elinw** [comment]
Fixed!

**Comment by siames3** [comment]
I have the same problem on Linux. I am getting the following error when I try to add a new document:

Zip file created: /home/user/Documents/qcoder/QCoderProject-qcode_project-2019-09-25.zip
Warning in gzfile(file, "rb") :
  cannot open compressed file '/home/user/Documents/qcoder/qcode_project/data_frames/qcoder_documents_qcode_project.rds', probable reason 'No such file or directory'
Warning: Error in gzfile: cannot open the connection
  76: gzfile
  75: readRDS
  74: qcoder::add_new_documents
  73: observeEventHandler [/home/user/R/x86_64-pc-linux-gnu-library/3.6/qcoder/shiny/qcoder/app.R#425]
   2: shiny::runApp
   1: qcode
