### ISSUE TITLE
Add create_empty_ for units, links, documents

### ISSUE THREAD

**Issue by elinw** [ropenscilabs/qcoder#78]
Right now when setting up a project an empty data frame is created for codes.  Let's do the same thing for the other data frames.

**Comment by FrdVnW** [comment]
the empty creation function was not ok for me for code, I found a little bug. I just PR a fix for that

**Comment by elinw** [comment]
Are you using the latest version? Because I merged the PR that fixed the missing slash.

**Comment by FrdVnW** [comment]
Yes the missing slash was in the 'create_empty_code_file' function, here is another one in the 'read_code_data', if I remembered.
(but I have to update also my branches)

**Comment by elinw** [comment]
So what we need to do is to take the code in `create_empty_code_file()` and  change it to `create_empty_file` and then enter the segment of the name indicating the type as an additional parameter. That will scale well when more types of data are added.

**Comment by elinw** [comment]
So I merged my fixes to the create_empty_code_file() function, if you could check to see if it is working for you that would be great, then we could move to the others.

**Comment by elinw** [comment]
This is addressed in #144
