### ISSUE TITLE
Change Rmd documents output from "md_document" to "github_document"

### ISSUE THREAD

**Issue by Yuri-M-Dias** [ropenscilabs/qcoder#84]
This is more of a suggestion in case you have more Rmd files being read from github.
The only difference might be the need to use a slightly more updated version of rmarkdown, [as per the docs](https://rmarkdown.rstudio.com/github_document_format.html).

I have used this locally to alter the README, as it creates a HTML preview for the file, so it's rendering correctly for it too.

**Comment by elinw** [comment]
I'm not sure about all the implications of this, but I feel the vast majority of readers will be on github so merged it.
