### ISSUE TITLE
Add a standard way of compiling/testing/development

### ISSUE THREAD

**Issue by Yuri-M-Dias** [ropenscilabs/qcoder#86]
While cloning this repo, I was at a loss how to properly install and test it. R CMD check would not execute the tests as they should be, so I ended up copying a Makefile from an old project and just using it. It's relying on devtools for the steps, however it'd be helpful if this was on the project.

I'm opening this issue with a PR for that. It might not be the way that you're developing it currently however, so if anyone could point me as to how it'd be really helpful.

Thanks in advance!

**Comment by elinw** [comment]
I'm not having any problem with R CMD check running the tests (I know because the fail plenty of times) but that's from inside RStudio.   Let's try to make it more generally useful.  Thanks!
